### PR TITLE
Add capability to mock inherited methods

### LINKED ISSUE #17: class level mocks and inheritance
Looking for some help.  I am trying to mock a class level method but seem to be doing something wrong.

``` crystal
require "spec"
require "mocks/spec"

class Base
  def self.hello
    puts "Hello"
  end
end

class Say < Base
  # def self.hello
  #   puts "Hello"
  # end
end

Mocks.create_mock Say do
  mock self.hello
end

describe Say do
  allow(Say).to receive(self.hello()).and_return("Hello")
  it "says Hello" do
    Say.hello.should eq "Hello"
  end
end
```

If the `self.hello` method is in the base class, I get the following error:

```
there is no previous definition of 'hello'
```

### PR DESCRIPTION
**Pull request by waterlink**
Fixes #17 

@drujensen Could you take a look? Maybe you can try it out on your project (add `branch: class-level-mocks-and-inheritance` to your `shard.yml` `mocks` dependency).

### CODE REVIEW

**Comment by drujensen** [comment]
:hammer:

**Comment by drujensen** [comment]
$crystal spec
.................................................

Finished in 1.94 milliseconds
49 examples, 0 failures, 0 errors, 0 pending

I verified that this worked for my sample test.  :+1:

**Comment by waterlink** [comment]
I have released `0.8.0` version with this change.

**Comment by drujensen** [comment]
Thanks @waterlink

**Pull request merged**
